server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:oracle:thin:@localhost:1521/xe
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: SCOTT
      password: TIGER


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always